config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'prototypes/ranking#index'
  resources :users, only: [:show, :edit, :update]
  resources :prototypes
  namespace :prototypes do
    resources :comments, only: :create
  end
  resources :tags, only: [:index, :show]
  resources :likes, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :prototype
  belongs_to :user

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :prototype, counter_cache: true
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :thumbnails, dependent: :destroy
  has_many :likes

  accepts_nested_attributes_for :thumbnails

  acts_as_taggable
  acts_as_ordered_taggable_on :prototypes

  paginates_per 8
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base

  belongs_to :prototype

  mount_uploader :name, ThumbnailUploader

  enum status: [:main, :sub]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prototypes
  has_many :comments
  has_many :likes

  mount_uploader :avatar, AvatarUploader

  paginates_per 8
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:user_name, :avatar, :member, :profile, :works]
    devise_parameter_sanitizer.for(:sign_in) << [:user_name, :avatar, :member, :profile, :works]
    devise_parameter_sanitizer.for(:account_update) << [:user_name, :avatar, :member, :profile, :works]
  end

  def after_sign_out_path_for(resouce)
    '/users/sign_in'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    current_user.likes.create(create_params)
    count = Like.where(prototype_id: params[:prototype_id]).count
    render json: { count: count }
  end

  def destroy
    like = Like.find_by(prototype_id: params[:prototype_id], user_id: current_user.id)
    like.destroy
    count = Like.where(prototype_id: params[:prototype_id]).count
    render json: { count: count }
  end

private

  def create_params
    params.permit(:prototype_id)
  end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController

  before_action :set_prototype, only: :create

  def create
    current_user.comments.create(comment_params)
    @comments = @prototype.comments
  end

private

  def set_prototype
    @prototype = Prototype.find(comment_params[:prototype_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :prototype_id)
  end

end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
end

app/controllers/prototypes/ranking_controller.rb
class Prototypes::RankingController < ApplicationController

  def index
    @prototypes = Prototype.order(likes_count: :desc).page(params[:page])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype, except: [:new, :create, :index]

  def index
    @prototypes = Prototype.order(created_at: :desc).page(params[:page])
  end

  def new
    @prototype = Prototype.new
    @prototype.thumbnails.build
  end

  def create
    @prototype = current_user.prototypes.new(create_params)
    if @prototype.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments
    @like_exists = @prototype.likes.where(user_id: current_user.id).exists?
  end

  def edit
  end

  def update
    @prototype.update(create_params) if @prototype.user_id == current_user.id
    redirect_to root_path
  end

  def destroy
    @prototype.destroy if @prototype.user_id == current_user.id
    redirect_to root_path
  end

  private
  def create_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :user_id, thumbnails_attributes: [:name, :prototype_id, :status]).merge(tag_list: params[:prototype][:tag])
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :set_tag, only: :show

  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @prototypes = Prototype.tagged_with(params[:name])
  end

private
  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(update_params)
    redirect_to root_path
  end

  private
  def update_params
    params.require(:user).permit(:user_name, :email, :member, :profile, :works, :avatar)
  end
end

app/helpers/prototype_helper.rb
module PrototypeHelper

  def proto_user
    @prototype.user
  end

  def main_image
    @prototype.thumbnails.main.first.name
  end

  def sub_images
    @prototype.thumbnails.sub
  end
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              %a{:href => "/users/sign_in"}
                Get Started
      - else
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", data: {toggle: "dropdown"}, href: "#", role: "button"}
              #{ current_user.user_name }
              %span.caret
            %ul.dropdown-menu{ role: "menu"}
              %li
                = link_to "My Page", user_path(current_user.id)
              %li
                = link_to "Profile Edit", edit_user_path(current_user.id)
              %li
                = link_to "Log out", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_prototype_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield

app/views/prototypes/_comment.html.haml
.media
  .media-left
    = link_to (image_tag comment.user.avatar, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;", class: 'media-object') , "/users/#{ comment.user.id }"
  .media-body
    %h4#top-aligned-media.media-heading
      #{ comment.user.user_name }
      %a.anchorjs-link{ href: "#top-aligned-media" }
        %span.anchorjs-icon
    %p #{ comment.text }

app/views/prototypes/_form.html.haml
= form_for [@prototype, @comment], url: prototypes_comments_path, html: { class: "form-inline" }, remote: true do |f|
  %h4 Write a comment
  .row
    .form-group.col-md-10
      = f.text_area :text, placeholder: "Your comments", rows: "3", class: "form-control", id: "comment_field"
      = f.hidden_field :prototype_id, value: @prototype.id
    .form-group.col-md-2
      = f.submit Comment, class: "btn btn-primary"

app/views/prototypes/_header.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          = link_to "Popular PROTO", root_path
        %li.active{ role: "presentation" }
          = link_to "Newest PROTO", prototypes_path
      = link_to 'View Tags', tags_path, class: "btn btn-default col-lg-1"

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag prototype.thumbnails.main.first.name
      - if user_signed_in? && current_user.id == prototype.user_id
        .more
          %ul.more_list
            %li
              = link_to "編集", edit_prototype_path(prototype.id), method: :get
            %li
              = link_to "削除", prototype_path(prototype.id), method: :delete
      .caption
        %h3 #{ prototype.title }
        .proto-meta
          .proto-user
            = link_to "by #{ prototype.user.user_name }", "/users/#{ prototype.user.id }"
          .proto-posted
            #{ prototype.created_at.strftime("%b %d") }
        %ul.proto-tag-list.list-inline
          - prototype.tags.each do |tag|
            %li
              = link_to "#{ tag.name }", tag_path(tag.id), class: "btn btn-default"

app/views/prototypes/comments/create.js.haml
:plain
  $('#comment_field').val('')
  $('#comments').html(
    "#{ j(render partial: 'prototypes/comment', collection: @comments) }"
  );
  $('.proto-comments .num').html("(#{ @comments.count } )");

app/views/prototypes/edit.html.haml
=form_for(@prototype, html: { class: "container proto-new" }, method: :patch) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        =f.text_field :title, placeholder: "Title", class: "proto-new-title"
    .row
      .col-md-12
        .cover-image-upload.img_preview
          = f.fields_for :thumbnails do |thumbnail|
            = thumbnail.file_field :name
            = thumbnail.hidden_field :status, value: :main
            = image_tag "", width: "100%", height: "100%", class: "preview"
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload.img_preview
              = f.fields_for :thumbnails do |thumbnail|
                = thumbnail.file_field :name
                = thumbnail.hidden_field :status, value: :sub
                = image_tag "", width: "100%", height: "100%", class: "preview"
          %li.list-group-item.col-md-4
            .image-upload.img_preview
              = f.fields_for :thumbnails do |thumbnail|
                = thumbnail.file_field :name
                = thumbnail.hidden_field :status, value: :sub
                = image_tag "", width: "100%", height: "100%", class: "preview"
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        =f.text_field :catch_copy, placeholder: "catch_copy"
      .col-md-12
        =f.text_area :concept, placeholder: "concept", cols: "30", rows: "4"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "UI"
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Application"
    .row.text-center.proto-btn
      %button.btn.btn-lg.btn-primary.btn-block{ type: "submit" } Update

app/views/prototypes/index.html.haml
= render "prototypes/header"
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/new.html.haml
=form_for(@prototype, html: {class: "container proto-new"}) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        =f.text_field :title, placeholder: "Title", class: "proto-new-title"
    .row
      .col-md-12
        .cover-image-upload.img_preview
          = f.fields_for :thumbnails do |thumbnail|
            = thumbnail.file_field :name
            = thumbnail.hidden_field :status, value: :main
            = image_tag "", width: "100%", height: "100%", class: "preview"
      .col-md-12
        %ul.proto-sub-list.list-group
          - 2.times do
            %li.list-group-item.col-md-4
              .image-upload.img_preview
                = f.fields_for :thumbnails do |thumbnail|
                  = thumbnail.file_field :name
                  = thumbnail.hidden_field :status, value: :sub
                  = image_tag "", width: "100%", height: "100%", class: "preview"
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        =f.text_field :catch_copy, placeholder: "catch_copy"
      .col-md-12
        =f.text_area :concept, placeholder: "concept", cols: "30", rows: "4"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "UI"
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Application"
    .row.text-center.proto-btn
      %button.btn.btn-lg.btn-primary.btn-block{ type: "submit" } Publish

app/views/prototypes/newest.html.haml
= render "prototypes/header"
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/ranking/index.haml
= render "prototypes/header"
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          %a{href: "/users/#{proto_user.id}"}
            %img.media-object{alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: "#{current_user.avatar}", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            #{ @prototype.title }
          .proto-user
            = link_to "by #{ proto_user.user_name }", "/users/#{proto_user.id}"
            %span.degree #{ proto_user.member }

    .col-md-6.text-right
      %button#like-button.btn.btn-default{ class: (@like_exists) ? "decrement" : "increment", data: { id: @prototype.id } }
        - if @like_exists
          = image_tag("icon_heart_red.svg", id: "like-heart")
          Like
        - else
          = image_tag("icon_heart.svg", id: "like-heart")
          Like
        %span.num#like-sum #{ @prototype.likes_count }
  .row
    .col-md-9
      = image_tag main_image, class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        - sub_images.each do |image|
          %li.list-group-item
            = image_tag image.name, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p #{ @prototype.catch_copy }
    .col-md-6
      %h4 Concept
      %p #{ @prototype.concept }
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          %li
            = link_to "#{ tag.name }", tag_path(tag.id), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (#{ @comments.count })
    .col-md-8
      #comments
        = render partial: "prototypes/comment", collection: @comments
      = render partial: "prototypes/form"

app/views/tags/index.html.haml
= render "prototypes/header"
.container.proto-list
  .row
    - @tags.each do |tag|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          = link_to "#{ tag.name }", tag_path(tag.id, name: tag.name), class: "btn btn-tag"
          .tag-meta
            = link_to tag_path(tag.id), class: "label label-default tag-list-number" do
              %i #{ tag.taggings.count } Projects

app/views/tags/show.html.haml
= render "prototypes/header"
.container
  .row
    .col-sm-12.proto-content
      .thumbnail
        = link_to "#{ @tag.name }", "/tags/#{ @tag.id }", class: "btn btn-tag"
        .tag-meta
          %a{href: "/tags/#{ @tag.id }", class: "label label-default tag-list-number"}
            #{ @tag.taggings_count }
            %i Projects
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} 4
    %li
      %a{:href => "#"} 5
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{"aria-hidden" => "true"} »

app/views/users/edit.html.haml
=form_for(@user, html: {class: "container user-new"}) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        .user-name_image.row
          .user-name.col-md-10
            =f.text_field :user_name, placeholder: "Username"
          .user-image.col-md-2{:style => "background-image: url(#{current_user.avatar});"}
            %button.btn.btn-primary Change image
            =f.file_field :avatar
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            =f.text_field :member, placeholder: "Member"
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            =f.text_area :profile, placeholder: "Profile", cols: "30", rows: "4"
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            =f.text_area :works, placeholder: "Works", cols: "30", rows: "4"
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Save

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{:href => "#"}
          %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "#{current_user.avatar}", :style => "width: 64px; height: 64px;"}/
      .media-body
        %h4#top-aligned-media.media-heading
          #{ current_user.user_name}
          %span.label.label-default.project-number
            #{ current_user.prototypes.count }
            %i Projects
        .proto-user
          %span.degree #{current_user.member}
        .row
          .col-md-6
            %h4 Profile
            %p #{current_user.profile}
          .col-md-6
            %h4 Works
            %p #{current_user.works}
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)